icons_format = "{icon}"

[theme]
theme = "native"
[theme.overrides]
idle_fg = "#fdf6e3"
idle_bg = "#282828"

[icons]
icons = "material-nf"

[[block]]
block = "cpu"
interval = 1
format = " $icon $frequency.eng(prefix:M,w:3) $utilization "
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "amd_gpu"
format = " $icon $utilization "
format_alt = " $icon MEM: $vram_used_percents ($vram_used/$vram_total) "
interval = 1

[[block]]
block = "temperature"
format = " $icon {$max}C "
format_alt = " $icon $min min, $max max, $average avg "
interval = 1
chip = "*-isa-*"


[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $ip $speed_down $speed_up|$ip $speed_down $speed_up}"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "


[[block]]
block = "memory"
format = " $icon $mem_avail_percents "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "sound"

#[[block]]
#block = "backlight"
#format = " $icon $brightness "
#step_width = 5

[[block]]
block = "battery"
format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m)} "

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%d/%m %R') "
